# -*- coding: utf-8 -*-
"""02_Makeover_Bigrams.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABusQ_ddn8CdzwPEyRCZqV-k1WGUyFuu
"""

words = open('/content/names.txt').read().split()

words[:10]

len(words)

min(len(w) for w in words)

for w in words[:1]:
  for ch1,ch2 in zip(w,w[1:]):
    print(ch1,ch2)

b = {}
for w in words:
  chs = ['<S>'] + list(w) + ['<E>']
  for ch1,ch2 in zip(chs,chs[1:]):
    bigram = (ch1,ch2)
    b[bigram] = b.get(bigram,0)+1

import torch

N = torch.zeros((27,27),dtype=torch.int32)

chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}

stoi

for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1,ch2 in zip(chs,chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    N[ix1,ix2] += 1

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

plt.figure(figsize=(16,16))
plt.imshow(N, cmap='Blues')
for i in range(27):
    for j in range(27):
        chstr = itos[i] + itos[j]
        plt.text(j, i, chstr, ha="center", va="bottom", color='gray')
        plt.text(j, i, N[i, j].item(), ha="center", va="top", color='gray')
plt.axis('off');

