# -*- coding: utf-8 -*-
"""03_Makemore_MLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HnElRq7MfBetepJXGwHTfAupK-G8CQYu
"""

# Commented out IPython magic to ensure Python compatibility.
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
# %matplotlib inline

words = open('/content/names.txt').read().split()
words[:8]

len(words)

chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
print(itos)

# build the dataset

block_size = 3 # context length: how many characters do we take to predict the next one?
X, Y = [], []
for w in words:

  #print(w)
  context = [0] * block_size
  for ch in w + '.':
    ix = stoi[ch]
    X.append(context)
    Y.append(ix)
    #print(''.join(itos[i] for i in context), '--->', itos[ix])
    context = context[1:] + [ix] # crop and append

X = torch.tensor(X)
Y = torch.tensor(Y)

X.shape, X.dtype, Y.shape, Y.dtype

C = torch.rand((27,2))

C[5]

# F.one_hot(torch.tensor(5),num_classes=27).float() @ C

C[X].shape

emb = C[X]
emb.shape

W1 = torch.randn((6,100))
b1 = torch.randn(100)

h = torch.tanh(emb.view(-1,6) @ W1 + b1)

h

# h = emb.view(emb.shape[0],6) @ W1 + b1

h.shape

W2 = torch.randn((100,27))
b2 = torch.randn(27)

logits = h @ W2 + b2

logits.shape

counts = logits.exp()

prob = counts / counts.sum(1,keepdim=True)

prob.shape

loss = -prob[torch.arange(228146),Y].log().mean()
loss

"""Summerizing"""

X.shape, Y.shape

g = torch.Generator().manual_seed(2147483647) # for reproducibility
C = torch.randn((27, 2), generator=g)
W1 = torch.randn((6, 100), generator=g)
b1 = torch.randn(100, generator=g)
W2 = torch.randn((100, 27), generator=g)
b2 = torch.randn(27, generator=g)
parameters = [C, W1, b1, W2, b2]

sum(p.nelement() for p in parameters)

for p in parameters:
  p.requires_grad = True

#setting learing rate
lre = torch.linspace(-3,0,1000)
lrs = 10**lre

lri = []
lossi = []

for i in range(1000):

  #mini batch construction
  ix = torch.randint(0,X.shape[0],(32,))

  #Forward Pass
  emb = C[X[ix]]
  h = torch.tanh(emb.view(-1,6) @ W1 + b1)
  logits = h @ W2 + b2
  loss = F.cross_entropy(logits,Y[ix])

  #backward pass
  for p in parameters:
    p.grad = None
  loss.backward()

  #update
  lr = lrs[i]
  for p in parameters:
    p.data += -lr*p.grad

  #Track
  lri.append(lre[i])
  lossi.append(loss.item())

print(loss.item())

"""Mini Batch"""

torch.randint(0,X.shape[0],(32,))

plt.plot(lri,lossi)

"""#Training, Testing, Validation/Dev Split"""

# build the dataset
block_size = 3 # context length: how many characters do we take to predict the next one?

def build_dataset(words):
  X, Y = [], []
  for w in words:

    #print(w)
    context = [0] * block_size
    for ch in w + '.':
      ix = stoi[ch]
      X.append(context)
      Y.append(ix)
      #print(''.join(itos[i] for i in context), '--->', itos[ix])
      context = context[1:] + [ix] # crop and append

  X = torch.tensor(X)
  Y = torch.tensor(Y)
  print(X.shape, Y.shape)
  return X, Y

import random
random.seed(42)
random.shuffle(words)
n1 = int(0.8*len(words))
n2 = int(0.9*len(words))

Xtr, Ytr = build_dataset(words[:n1])
Xdev, Ydev = build_dataset(words[n1:n2])
Xte, Yte = build_dataset(words[n2:])

C = torch.rand((27,2))

Xtr.shape, Ytr.shape

lri = []
lossi = []

for i in range(10000):

  #mini batch construction
  ix = torch.randint(0,Xtr.shape[0],(32,))

  #Forward Pass
  emb = C[Xtr[ix]]
  h = torch.tanh(emb.view(-1,6) @ W1 + b1)
  logits = h @ W2 + b2
  loss = F.cross_entropy(logits,Ytr[ix])

  #backward pass
  for p in parameters:
    p.grad = None
  loss.backward()

  #update
  lr = lrs[i]
  for p in parameters:
    p.data += -lr*p.grad

  #Track
  lri.append(lre[i])
  lossi.append(loss.item())

print(loss.item())

